# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-04 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='token',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
