# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-19 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20180303_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='fb_social_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gh_social_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
