# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-03 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='max_hackers',
            field=models.IntegerField(default=100),
        ),
    ]
