# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-04 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_settings_max_hackers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='confirmation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hackathon_end',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hackathon_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='registration_close',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='registration_open',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
