# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180303_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='max_bus_spots',
            field=models.IntegerField(default=32),
        ),
    ]
