# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('age', models.IntegerField()),
                ('university', models.CharField(max_length=100)),
                ('enroll_year', models.IntegerField(null=True)),
                ('diet', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('special_needs', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('shirt_size', models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G')], max_length=3)),
                ('cv_type', models.CharField(choices=[('LI', 'LinkedIn'), ('GH', 'GitHub'), ('WS', 'Website'), ('OT', 'Outro')], max_length=3)),
                ('cv', models.CharField(max_length=300)),
                ('cv2_type', models.CharField(blank=True, choices=[('LI', 'LinkedIn'), ('GH', 'GitHub'), ('WS', 'Website'), ('OT', 'Outro')], max_length=3, null=True)),
                ('cv2', models.CharField(blank=True, max_length=300, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('essay', models.TextField(blank=True, null=True)),
                ('sleeping_bag', models.BooleanField(default=False)),
                ('pillow', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('checked_in', models.BooleanField(default=False)),
                ('withdraw', models.BooleanField(default=False)),
                ('fb_social_id', models.CharField(max_length=50, null=True, unique=True)),
                ('gh_social_id', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('project', models.CharField(default='', max_length=300)),
                ('location', models.CharField(default='', max_length=20)),
                ('block_new_members', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='hacker',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hackers', to='hackers.Team'),
        ),
        migrations.AddField(
            model_name='hacker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='hacker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hackers.Hacker'),
        ),
    ]
