# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='azure_pass',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='shirt_size',
            field=models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=3),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='fb_social_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='gh_social_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
