# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0003_auto_20171017_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='github_url',
            field=models.URLField(default=''),
        ),
    ]
