# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0004_team_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='github_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
