# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-02 03:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0006_hacker_second_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='shirt_style',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Babylook', 'Babylook')], default='Normal', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18, 'A idade mínima é 18 anos.')]),
        ),
    ]
