# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-03 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0012_hacker_waitlist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='waitlist',
            field=models.BooleanField(default=False),
        ),
    ]
