# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-03 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0013_hacker_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='waitlist_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
