# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-03 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0014_auto_20180303_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='verification_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
