# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-06 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0015_hacker_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('NA', 'Prefiro não dizer')], max_length=2),
        ),
    ]
