# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-13 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0016_auto_20180306_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bus_sc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='bus_sp',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv_type',
            field=models.CharField(blank=True, choices=[('LI', 'LinkedIn'), ('GH', 'GitHub'), ('WS', 'Website'), ('OT', 'Outro')], max_length=3, null=True),
        ),
    ]
