# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0017_auto_20180313_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
