# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-08 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0020_auto_20180327_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='github_url',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
