# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-27 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackers', '0006_hacker_second_chance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('kind', models.CharField(choices=[('Workshop', 'Workshop'), ('Palestra', 'Palestra'), ('Tech Talk', 'Tech Talk'), ('Refeição', 'Refeição'), ('Meta', 'Meta')], max_length=30)),
                ('requires_registration', models.BooleanField(default=False)),
                ('speaker', models.CharField(blank=True, max_length=100, null=True)),
                ('speaker_description', models.TextField(blank=True, null=True)),
                ('max_attendees', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='schedule.Event'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='hacker',
            field=models.ManyToManyField(related_name='events_attended', to='hackers.Hacker'),
        ),
    ]
