# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-27 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20171027_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='feedback',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
