# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-04 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20171027_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
